name:           Ordered Custom Fields
key:            OrderedCF
id:             OrderedCF
plugin_class:   OrderedCF
schema_version: 14

object_types:
    permission:
        page_prefs:     text meta
        category_prefs: text meta
        folder_prefs:   text meta
        author_prefs:   text meta

callbacks:
    post_init:                  $OrderedCF::OrderedCF::post_init
    template_source.edit_entry: $OrderedCF::OrderedCF::App::replace_prefs_save_mode
    template_param.cfg_entry:   $OrderedCF::OrderedCF::App::remove_entry_display_cfg

upgrade_functions:
    permission_meta_table:
        priority: 1
        version_limit: 14
        code: $OrderedCF::OrderedCF::Upgrade::create_table_permission_meta

applications:
    cms:
        methods:
            orderedcf_save_prefs: $OrderedCF::OrderedCF::App::mode_save_prefs
