name:           Ordered Custom Fields
version:        1.0.1
description:    A plugin which enables reordering and saving custom and native field order for an individual user or as a blog default.
author_name:    Jay Allen, Endevver LLC
author_link:    http://endevver.com/
key:            OrderedCF
id:             OrderedCF
plugin_class:   OrderedCF
schema_version: 1

object_types:
    permission:
        page_prefs:     text meta
        category_prefs: text meta
        folder_prefs:   text meta
        author_prefs:   text meta

init_request: $OrderedCF::OrderedCF::init_request

callbacks:
    post_init:                  $OrderedCF::OrderedCF::post_init
    template_source.edit_entry: $OrderedCF::OrderedCF::App::replace_prefs_save_mode
    template_param.cfg_entry:   $OrderedCF::OrderedCF::App::remove_entry_display_cfg
    template_param.edit_entry:  $OrderedCF::OrderedCF::App::insert_blog_default_option

upgrade_functions:
    permission_meta_table:
        priority: 1
        version_limit: 1
        code: $OrderedCF::OrderedCF::Upgrade::create_table_permission_meta

applications:
    cms:
        methods:
            orderedcf_save_prefs: $OrderedCF::OrderedCF::App::mode_save_prefs
